(function () {
  window.WhatsAppSelectors = {
    messageInput: [
      '#main footer div[contenteditable="true"]',
      '#main footer div[role="textbox"]',
      '#main footer p.selectable-text',
      '#main div[contenteditable="true"][data-tab]',
      'div[contenteditable="true"][role="textbox"]',
      'div[contenteditable="true"][data-tab="10"]',
      'div[contenteditable="true"][data-tab="6"]',
      '#main footer p',
      'div[contenteditable="true"]',
    ],
    sendButton: [
      '#main footer button[aria-label*="Enviar"]',
      '#main footer button[aria-label*="Send"]',
      '#main footer button span[data-icon="send"]',
      '#main footer span[data-icon="send"]',
      '#main footer span[data-icon="send-v2"]',
      'button[aria-label*="Enviar"]',
      'button[aria-label*="Send"]',
      'span[data-icon="send"]',
      'span[data-icon="send-v2"]',
    ],
    searchButton: [
      '#side button[aria-label*="Pesquisar"]',
      '#side button[aria-label*="Search"]',
      '#side button[data-tab="2"]',
      '#side label',
      'span[data-icon="search"]',
    ],
    searchInput: [
      '#side div[contenteditable="true"][role="textbox"]',
      '#side div[contenteditable="true"][data-tab="3"]',
      '#side label div div[contenteditable="true"]',
      '#side div[contenteditable="true"]',
      'div[contenteditable="true"][data-tab="3"]',
      'div[title="Caixa de texto de pesquisa"]',
      'div[title="Search input textbox"]',
      'div[aria-label="Caixa de texto de pesquisa"]',
      'div[aria-label="Search input textbox"]',
      '#side p.selectable-text',
    ],
    searchResultItem: [
      '#side div[role="grid"] div[role="listitem"]',
      '#side div[data-testid="cell-frame-container"]',
      '#side div[role="row"]',
      '#side div._ak72',
      '#side div._ak73',
      '#side div._aov8',
      '#side span[title]',
    ],
    activeChatHeaderTitle: [
      '#main header div[role="button"] h2 span[title]',
      '#main header div[role="button"] span[title]:first-child',
      '#main header div[role="button"] span._ao3e',
      '#main header div[role="button"] h2',
      '#main header div[role="button"] span[dir="auto"]',
      '#main header span[title]:not([title=""]):not([title*="clique"]):not([title*="Mensagens"]):not([title*="dados"])',
    ],
    activeChatHeaderAvatar: [
      '#main header img[src*="whatsapp.net"]',
      '#main header img',
    ],
  };
})();
