(function () {
  window.WhatsAppSelectors = {
    messageInput: [
      '#main footer div[contenteditable="true"]',
      '#main footer div[role="textbox"]',
      '#main footer p.selectable-text',
      '#main div[contenteditable="true"][data-tab]',
      'div[contenteditable="true"][role="textbox"]',
      'div[contenteditable="true"][data-tab="10"]',
      'div[contenteditable="true"][data-tab="6"]',
      '#main footer p',
      'div[contenteditable="true"]',
    ],
    sendButton: [
      '#main footer button[aria-label*="Enviar"]',
      '#main footer button[aria-label*="Send"]',
      '#main footer button span[data-icon="send"]',
      '#main footer span[data-icon="send"]',
      '#main footer span[data-icon="send-v2"]',
      'button[aria-label*="Enviar"]',
      'button[aria-label*="Send"]',
      'span[data-icon="send"]',
      'span[data-icon="send-v2"]',
    ],
    searchButton: [
      '#side button[aria-label*="Pesquisar" i]',
      '#side button[aria-label*="Search" i]',
      '#side [data-testid="search"]',
      '#side [data-testid="chat-list-search-button"]',
      '#side span[data-icon="search"]',
      '#side span[data-icon="search-v2"]',
      'button[aria-label*="Pesquisar" i]',
      'button[aria-label*="Search" i]',
      '#side button[data-tab="2"]',
      '#side button[data-tab="3"]',
      '#side label',
      'span[data-icon="search"]',
      'span[data-icon="search-v2"]',
    ],
    searchInput: [
      '#side [data-testid="chat-list-search"] input',
      '#side [data-testid="chat-list-search"] [contenteditable="true"]',
      '#side [data-testid="chat-list-search"] p',
      '#side [data-testid="chat-list-search"]',
      '[data-testid="chat-list-search"] input',
      '[data-testid="chat-list-search"] [contenteditable="true"]',
      '[data-testid="chat-list-search"] p',
      '[data-testid="chat-list-search"]',
      '[data-testid="search-input"] input',
      '[data-testid="search-input"] [contenteditable="true"]',
      '[data-testid="search-input"] p',
      '[data-testid="search-input"]',
      '#side input[type="text"]',
      '#side input[type="search"]',
      '#side input[role="combobox"]',
      '#side input',
      '#side div[contenteditable="true"][role="textbox"]',
      '#side div[contenteditable="true"][data-tab="3"]',
      '#side div[role="textbox"] p',
      '#side div[role="textbox"]',
      '#side label div div[contenteditable="true"]',
      '#side label input',
      '#side label div[contenteditable="true"]',
      '#side div[contenteditable="true"]',
      '#side p[contenteditable="true"]',
      '#side p.selectable-text',
      '#side [data-tab="3"]',
      'div[contenteditable="true"][data-tab="3"]',
      'div[title*="pesquisa" i]',
      'div[title*="search" i]',
      'div[aria-label*="pesquisa" i]',
      'div[aria-label*="search" i]',
      'input[placeholder*="pesquisar" i]',
      'input[placeholder*="search" i]',
      'input[aria-label*="pesquisar" i]',
      'input[aria-label*="search" i]',
      '#side [data-lexical-editor="true"]',
      'div[role="search"] input',
      'div[role="search"] [contenteditable="true"]',
    ],
    searchResultItem: [
      '#side div[role="grid"] div[role="listitem"]',
      '#side div[data-testid="cell-frame-container"]',
      '#side div[role="row"]',
      '#side div._ak72',
      '#side div._ak73',
      '#side div._aov8',
      '#side span[title]',
    ],
    activeChatHeaderTitle: [
      '#main header div[role="button"] h2 span[title]',
      '#main header div[role="button"] span[title]:first-child',
      '#main header div[role="button"] span._ao3e',
      '#main header div[role="button"] h2',
      '#main header div[role="button"] span[dir="auto"]',
      '#main header span[title]:not([title=""]):not([title*="clique"]):not([title*="Mensagens"]):not([title*="dados"])',
    ],
    activeChatHeaderAvatar: [
      '#main header img[src*="whatsapp.net"]',
      '#main header img',
    ],
  };
})();
